apiVersion: v1
kind: Service
metadata:
    name: mirrorlit-service
spec:
    selector:
        app: mirrorlit
    ports:
        - name: mirrorlit
          protocol: TCP
          port: 80
          targetPort: 3000
    type: LoadBalancer
